name: Daily Date Fact

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bun Setup
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Run dev build
        run: bun run dev

      - name: Update daily fact
        run: |
          git config --global user.name "saibhaskar421@gmail.com"
          git config --global user.email "Bhaskar422"
          git add README.md
          git commit -m "Updated daily fact"
          git push origin main
